spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.229.151:3306/gulimall_oms
    username: root
    password: meizu271
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-order
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000