spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  oss:
    accessKeyId:
    bucketName: 
    accessKeySecret:
    bucketDomain: http://guliyyds.oss-cn-hangzhou.aliyuncs.com #地址连接官网

   
server:
  port: 30000
