spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  oss:
    accessKeyId: LTAI5t7Fu48gHS2ZzQshgNBi  #密钥
    bucketName: guliyyds                   #用户
    accessKeySecret: yAo0aZnlctBgGvBGpYrJysWzAVRFe0  #密钥
    bucketDomain: http://guliyyds.oss-cn-hangzhou.aliyuncs.com #地址连接官网
    #endPoint: http://oss-cn-hangzhou.aliyuncs.com   #返回url地址
    endPoint: oss-cn-hangzhou.aliyuncs.com  #服务费签名
server:
  port: 30000